/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>

#line 1 "asd.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "s21_string.h"

START_TEST(strlen1)
{
#line 7
char string[10] = "hello world";
ck_assert_int_eq(strlen(string), s21_strlen(string));

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strlen1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
